export const movieConstants = {
  MOVIES_START: 'MOVIES_START',
  CHARACTER_START: 'CHARACTER_START',

  GET_MOVIES_SUCCESS: 'GET_MOVIES_SUCCESS',
  GET_MOVIES_FAILURE: 'GET_MOVIES_FAILURE',

  SET_MOVIE_SUCCESS: 'SET_MOVIE_SUCCESS',
  SET_MOVIE_FAILURE: 'SET_MOVIE_FAILURE',

  GET_CHARACTER_SUCCESS: 'GET_CHARACTER_SUCCESS',
  GET_CHARACTER_FAILURE: 'GET_CHARACTER_FAILURE',
};
